### ISSUE TITLE
http://mk85.republika.pl больше недоступен.

### ISSUE THREAD

**Issue by Klapautsiy** [shaos/nedoMK85#1]
здравствуй.
и, крутилось же в голове - заархивировать сайт.
случайно, не завалялось архива материалов сайта или в курсе, куда переехал, если переехал.
спасибо.

**Comment by shaos** [comment]
да, чото отвалилось

но на такой случай есть вебархив ;)

https://web.archive.org/web/20180201064014/http://mk85.republika.pl/rom.html
